### ISSUE TITLE
Deploy using --public

### ISSUE THREAD

**Issue by MiniGod** [jxom/micro-giphy-translate#3]
I wanted to make a pull request for gif.now.sh, but had a hard time finding this repo.

If you'd publish using `--public` I'd be able to read the [`/_src/package.json`](https://gif.now.sh/_src/package.json) and find this repo much faster.
Might help the next person :+1:

**Comment by jxom** [comment]
Done! 👍

**Comment by MiniGod** [comment]
Looks like you forgot `--public` :speak_no_evil: 

I wonder if there is a way to configure now to always deploy using `--public`? Maybe in `now.json`?

**Comment by jxom** [comment]
Maybe I'll look at integrating with Circle CI when I have the time :)

**Comment by jxom** [comment]
It's now public.

**Comment by MiniGod** [comment]
Looks like you can set `"public": true` in now.json!

https://zeit.co/docs/features/configuration#`public`-(boolean)

([thanks][thanks] @hawkins)

[thanks]: https://zeit-community.slack.com/archives/C1TMPLCKS/p1496849847426461?thread_ts=1496835685.150405&cid=C1TMPLCKS
